### ISSUE TITLE
Support Joins where column name is different from field

### ISSUE THREAD

**Issue by Roel** [DOV-Vlaanderen/pydov#152]
Currently, we can use Join to chain different searches using a common column name.

It would be nice to extend this to be able to Join a dataframe using a specified column name, that way we would be able to join f.ex. GrondwaterFilter with Boring.

F.ex.:
```
fs = GrondwaterFilterSearch()
bs = BoringSearch()

df_filters = fs.search(location=Box()), return_fields=('pkey_filter', 'boringfiche')
df_boringen = bs.search(query=Join(df_filters, on='pkey_boring', using='boringfiche'))
```

**Comment by pjhaest** [comment]
Ok, nice. I didn't know yet about the Join functionality in owslib. 
But if I understand correctly, this does not resolve #151 (even if the column name would be the same)? Because in #151 you query for something that does not exist?

Maybe it's easiest to adapt the column names of the different types in the dataframe to the same definition, now that we did not yet release anything? For example, change 'gw_id' in GrodwaterFilterSearch() to 'putnummer' of the BoringSearch()? That way we can use to above Join without having to do much remapping of column names for the joins?

**Comment by Roel** [comment]
The Join query is pydov specific: see the [docs](https://pydov.readthedocs.io/en/latest/query_attribute.html#join-different-searches).

I do agree that more consistency in naming would be good. While we can rename fields that are included in the default dataframes at the pydov side, this cannot be done for all other fields (f.ex. 'boringfiche' in the Filter service). They would need updating in the services themselves.

**Comment by Roel** [comment]
Progress can be tracked in the `join-using` branch.
