### ISSUE TITLE
open xml in memory

### ISSUE THREAD

**Issue by pjhaest** [DOV-Vlaanderen/pydov#299]
For people making use of cloud platforms it can be useful to read the xml data in memory, instead of parsing the download

**Comment by Roel** [comment]
I don't understand a word of what you're trying to say here :smile: 
But we can certainly elaborate during the code sprint.

**Comment by pjhaest** [comment]
I don't understand either, but I thought it could be convenient to not write xml to temp folders but read directly to dataframes. Or does the request automatically imply a download to file? Haven't looked at it yet 😉
Yust a thought, not necessary

**Comment by Roel** [comment]
Yes, in order to be able to read and parse the XML data, it needs to be downloaded first. Sending the request does not imply writing the result to disk (if that is what you mean by 'downloading a file').

Whether or not the downloaded XML data is written to disk depends on your caching settings and how that cache is implemented. By default, we use a caching implementation that writes the XML data to disk as gzipped ascii files.

You can always [disable caching](https://pydov.readthedocs.io/en/stable/caching.html#disabling-the-cache) to prevent writing the XML data to disk, or implement an [alternative cache](https://pydov.readthedocs.io/en/stable/caching.html#implementing-custom-caching) that stores data in memory or another distributed cache system (like Redis, etc.).

**Comment by pjhaest** [comment]
:+1:
