### ISSUE TITLE
improve issue/PR templates

### ISSUE THREAD

**Issue by stijnvanhoey** [DOV-Vlaanderen/pydov#43]
according to https://github.com/blog/2495-multiple-issue-and-pull-request-templates, we can better adapt the template to specific reasons fo issues

**Comment by pjhaest** [comment]
+1 if a template for debugging is provided

**Comment by johanvdw** [comment]
I'm a bit reluctant: at least in the current state of the project I think this is overkill, and quite frankly I think it will remain like that. You don't want people to mail you because they didn't understand how to open a ticket. 

If it doesn't solve a problem, it only adds to the project complexity, actually increasing the threshold for contributing.

I think we should encourage users as much as possible to give feedback/ask questions, and when we feel that important information is often missing, we can adjust the templates.

**Comment by pjhaest** [comment]
I was a bit confused with the current template that is aimed towards users of the master version. If we agree to use that template anyway for development, no problem. 
This is kind of related to the discussion about new development PRs in master, or in separate branches. I didn't remember the outcome of that discussion. I like it as it is now, with separate branches. This makes it easy to track down changes later on, no? Drawback is the confusion if multiple people start developing  on the same topic. Any comments?

**Comment by stijnvanhoey** [comment]
So, we keep the issue and PR templates as they are now, no further complexity addition required.
