### ISSUE TITLE
Hydrogeologische stratigrafie naming inconsistent at DOV

### ISSUE THREAD

**Issue by pjhaest** [DOV-Vlaanderen/pydov#67]
I found the naming of the 'hydrogeologische stratigrafie' confusing because its element in the xml is 'hydrogeologischeinterpretatie'.
I currently use the latter in pydov, to be adjusted if deemed necessary.

**Comment by Roel** [comment]
I would prefer the WFS naming. Since all of these are considered 'interpretaties', 'hydrogeologische stratigrafie' gives a little more information.

I don't think we'll change the XML schema in this regard anytime soon, but the pydov user is not dealing with XML directly so this shouldn't be too much of a problem I think.

**Comment by pjhaest** [comment]
Ok, reasonable
